# Generated by Django 6.1 on 2026-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='video',
            field=models.FileField(blank=True, upload_to='static/vids/'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
