# Generated by Django 6.1 on 2026-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_createpost_video_alter_createpost_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='createpost',
            name='video',
        ),
        migrations.AddField(
            model_name='createpost',
            name='media',
            field=models.FileField(default=1, upload_to='static/media/'),
            preserve_default=False,
        ),
    ]
