# Generated by Django 6.1 on 2026-08-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_createpost_image_remove_createpost_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='updated',
        ),
        migrations.AlterField(
            model_name='createpost',
            name='media',
            field=models.FileField(upload_to='home/static/media/'),
        ),
    ]
