# Generated by Django 6.1 on 2026-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_createpost_updated_alter_createpost_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='media',
            field=models.FileField(max_length=255, upload_to='home/static/media/'),
        ),
    ]
